[tool.ruff]
# Specify the paths or directories you want to exclude
exclude = ["notebooks", "migrations"]

# You can also configure additional settings, such as:
# Max line length (optional)
line-length = 88

# Enable specific rules (optional)
select = ["E", "F", "W"]

# Disable specific rules (optional)
ignore = ["E501"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 88
