name: Pull request rules

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  enforce-pr-title:
    name: Enforce PR title
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.DEVOPS_BOT_ACCESS_TOKEN }}
        script: |
          const REGEX = RegExp("([A-Z]{2,4}-\\d{1,5})\\s?\\|\\s?(.+)");
 
          const { title } = context.payload.pull_request;
          
          if (!REGEX.test(title)) {
            core.setFailed(
              `Pull Request title "${title}" failed to match regex - ${REGEX}`
            );
            return;
          }

  enforce-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "ignore-for-release, Semver-Major, breaking-change, Semver-Minor, enhancement, bug-fix, documentation, test, chore, ci, build, refactor, style, perf, revert, security, dependency"
